// postManagnmentSystem/postManagnmentSystemFrontEnd/src/pages/login.jsx
import React, { useState } from "react";
import { useAuth } from "../context/AuthContext"; // adjust path if needed
import { Link, useNavigate } from "react-router-dom";

const Login = () => {
    const { login } = useAuth();
    const [role, setRole] = useState("user");
    const [formData, setFormData] = useState({ email: "", password: "" });
    const navigate = useNavigate();

    const handleChange = (e) =>
        setFormData({ ...formData, [e.target.name]: e.target.value });

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            await login(formData, role);
            navigate(role === "admin" ? "/admin-dashboard" : "/user-dashboard");
        } catch (err) {
            console.error("Login failed", err.response?.data?.message);
        }
    };

    return (
        <div className="max-w-md mx-auto mt-10 p-4 border rounded shadow">
            <h2 className="text-xl font-bold mb-4">Login as {role}</h2>
            <select
                className="mb-4 border p-2 w-full"
                value={role}
                onChange={(e) => setRole(e.target.value)}
            >
                <option value="user">User</option>
                <option value="admin">Admin</option>
            </select>

            <form onSubmit={handleSubmit}>
                <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    className="mb-3 p-2 border w-full"
                    value={formData.email}
                    onChange={handleChange}
                    required
                />
                <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    className="mb-3 p-2 border w-full"
                    value={formData.password}
                    onChange={handleChange}
                    required
                />
                <button
                    type="submit"
                    className="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700"
                >
                    Login
                </button>
                <Link to="/register" className="mt-2">
                    Don't have an account? Register
                </Link>
            </form>
        </div>
    );
};

export default Login;

// postManagnmentSystem/postManagSystemFEVue/src/pages/login.vue
<!-- src/pages/LoginPage.vue -->
<template>
    <div class="max-w-md mx-auto mt-10 p-4 border rounded shadow">
        <h2 class="text-xl font-bold mb-4">Login as {{ role }}</h2>
        <select class="mb-4 border p-2 w-full" v-model="role">
            <option value="user">User</option>
            <option value="admin">Admin</option>
        </select>

        <form @submit.prevent="handleSubmit">
            <input
                v-model="formData.email"
                type="email"
                name="email"
                placeholder="Email"
                class="mb-3 p-2 border w-full"
                required
            />
            <input
                v-model="formData.password"
                type="password"
                name="password"
                placeholder="Password"
                class="mb-3 p-2 border w-full"
                required
            />
            <button
                type="submit"
                class="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700"
            >
                Login
            </button>
            <router-link
                to="/register"
                class="mt-2 block text-center text-blue-500 hover:underline"
            >
                Don't have an account? Register
            </router-link>
        </form>
    </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "../stores/auth.js";

const router = useRouter();
const authStore = useAuthStore();

const role = ref("user");
const formData = ref({
    email: "",
    password: "",
});

const handleSubmit = async () => {
    try {
        await authStore.login(formData.value, role.value);
        router.push(
            role.value === "admin" ? "/admin-dashboard" : "/user-dashboard"
        );
    } catch (err) {
        console.error(
            "Login failed",
            err.response?.data?.message || err.message
        );
    }
};
</script>
